'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bookmark Added..
        '''</summary>
        Friend ReadOnly Property EnMessageAddBookmark() As String
            Get
                Return ResourceManager.GetString("EnMessageAddBookmark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to is Empty..
        '''</summary>
        Friend ReadOnly Property EnMessageEmptySite() As String
            Get
                Return ResourceManager.GetString("EnMessageEmptySite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU Menu Cleared..
        '''</summary>
        Friend ReadOnly Property EnMessageMRUMenuClear() As String
            Get
                Return ResourceManager.GetString("EnMessageMRUMenuClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Contents ....
        '''</summary>
        Friend ReadOnly Property EnStatusTextLoadTreeContent() As String
            Get
                Return ResourceManager.GetString("EnStatusTextLoadTreeContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Files ....
        '''</summary>
        Friend ReadOnly Property EnStatusTextLoadTreeFile() As String
            Get
                Return ResourceManager.GetString("EnStatusTextLoadTreeFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scaning .
        '''</summary>
        Friend ReadOnly Property EnStatusTextReadingSite() As String
            Get
                Return ResourceManager.GetString("EnStatusTextReadingSite", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ico101() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico101", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ico103() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ico103", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SiteIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SiteIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property SP0010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SP0010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xrlin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xrlin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
